version: 2
updates:
  # ğŸ”§ Dev Container updates (Dockerfile, devcontainer.json)
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # âš™ï¸ GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      # ignore updates
      - dependency-name: "actions/setup-python"
        versions: ["*"]

  # ğŸ Python dependencies (src/requirements.txt)
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # ğŸ³ Dockerfile in root
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
